In [1]:
import torch

In [10]:
mytens = torch.tensor([[1,2,3], [4, 5, 6]], dtype = torch.float32, device = 'cpu', requires_grad = True)

In [11]:
print(mytens)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tens2 = torch.tensor([1,2,3], device = device)

In [13]:
tens2

tensor([1, 2, 3])

In [14]:
tens2.device

device(type='cpu')

In [16]:
tens2.requires_grad

False

In [17]:
tens2.dtype

torch.int64

In [18]:
tens2.shape

torch.Size([3])

In [19]:
tens2.size

<function Tensor.size>

In [20]:
mytens.shape

torch.Size([2, 3])

In [30]:
#torch.empty provides random data, could be anything not necessarily zeros, it gives what is available in the memory

In [31]:
x = torch.empty([2, 3])

In [32]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
torch.ones([4, 5])

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [38]:
#rand for uniform distribution with the interval [0, 1)

In [34]:
torch.rand((3,3))

tensor([[0.5208, 0.5960, 0.6626],
        [0.4807, 0.1367, 0.0549],
        [0.8553, 0.6094, 0.6212]])

In [39]:
#randn for normal distrivution with mean 0 and variance 1

In [53]:
normal_tensor = torch.randn(size = (3, 3))

In [54]:
normal_tensor.mean()

tensor(-0.0268)

In [55]:
normal_tensor.std()

tensor(1.1168)

In [56]:
normal_tensor.var()

tensor(1.2472)

In [58]:
normal = torch.normal(size = (3, 3), mean = 1.2, std = 3)

In [59]:
normal

tensor([[ 0.0434,  0.6397,  3.0000],
        [ 1.0067,  0.8092,  3.0705],
        [ 2.2196,  2.8337, -3.6607]])

In [60]:
normal.mean()

tensor(1.1069)

In [62]:
normal.std()

tensor(2.1165)

In [36]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [68]:
range_tensor = torch.arange(start = 0, end = 10 ,step = 2)

In [69]:
range_tensor

tensor([0, 2, 4, 6, 8])

In [71]:
lins_tensor = torch.linspace(start = 0, end = 10, steps = 20)

In [72]:
lins_tensor

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [74]:
torch.empty((1, 3)).normal_(mean = 0.2, std = 2)

tensor([[ 2.5720,  3.4372, -2.9986]])

In [75]:
torch.rand((1, 3)).normal_(mean = 0.2, std = 2)

tensor([[ 3.5902,  3.9319, -3.1076]])

In [76]:
torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [77]:
torch.diag(torch.eye(3))

tensor([1., 1., 1.])

In [78]:
torch.ones(3)

tensor([1., 1., 1.])

In [79]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [83]:
lins_tensor[lins_tensor.bool()].size()

torch.Size([19])

In [84]:
lins_tensor.size()

torch.Size([20])

In [85]:
lins_tensor.dtype

torch.float32

In [86]:
lins_tensor.half().dtype

torch.float16

In [89]:
lins_tensor.double().dtype

torch.float64

In [90]:
## array to tensor conversion

In [91]:
import numpy as np

In [93]:
arr = np.array([[1,2], [3, 4]])
tensor = torch.from_numpy(arr)

In [94]:
tensor

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [97]:
arr_back = tensor.numpy()

In [98]:
arr_back

array([[1, 2],
       [3, 4]])

In [99]:
## Math and comparison operations

In [100]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5,6])

x+y

tensor([5, 7, 9])

In [101]:
torch.add(x, y)

tensor([5, 7, 9])

In [102]:
torch.subtract(x, y)

tensor([-3, -3, -3])

In [103]:
torch.divide(x, y)

tensor([0.2500, 0.4000, 0.5000])

In [104]:
torch.true_divide(x, y)

tensor([0.2500, 0.4000, 0.5000])

In [106]:
# operations inpkace. t.add_ -> operation followed by _ 

In [111]:
t = torch.zeros((2, 3))

In [112]:
t.add_(x) # same as t = t+x

tensor([[1., 2., 3.],
        [1., 2., 3.]])

In [113]:
t.pow_(2)

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [115]:
t>2

tensor([[False,  True,  True],
        [False,  True,  True]])

In [120]:
t[t>2]

tensor([4., 9., 4., 9.])

In [121]:
# matrix multiplication
x = torch.rand((2, 3))
y = torch.rand((3, 2))


In [123]:
z = torch.mm(x, y)

In [124]:
z

tensor([[0.5055, 0.6279],
        [0.8489, 1.3287]])

In [127]:
torch.multiply(x, x)

tensor([[0.5812, 0.3259, 0.1211],
        [0.2147, 0.9065, 0.9919]])

In [128]:
x

tensor([[0.7624, 0.5709, 0.3481],
        [0.4633, 0.9521, 0.9960]])

In [132]:
x = torch.rand(2, 2)
x

tensor([[0.7638, 0.8974],
        [0.9472, 0.8714]])

In [134]:
x.matrix_power(2)

tensor([[1.4334, 1.4675],
        [1.5488, 1.6094]])

In [137]:
 # matrix power is only for x*x matrices

In [138]:
# z = x*y gives elemen wise multiplication

In [145]:
x = torch.rand(3)
y = torch.rand(3)

In [146]:
x

tensor([0.1485, 0.0440, 0.9965])

In [147]:
y

tensor([0.2803, 0.5495, 0.0267])

In [148]:
torch.dot(x, y)

tensor(0.0925)

In [149]:
x = torch.rand(2, 3)
y = torch.rand(2,3)

In [151]:
torch.dot(x, y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [155]:
# batch matrix multiplcation -> used when dimension is more than rows and cols

In [161]:
batch = 3
n = 2
m = 4
t1 = torch.rand(batch, n, m)
t2 = torch.rand(batch, m, n)

In [166]:
torch.bmm(t1, t2).size() #gives (batch, n,n as n*m x m*n gives n *n)

torch.Size([3, 2, 2])

In [168]:
# broadcasting
x1 = torch.rand(5, 5)
x2 = torch.rand(1, 5)

In [169]:
x1-x2

tensor([[ 0.6246,  0.7518, -0.4803,  0.1056,  0.1675],
        [ 0.5643,  0.0711, -0.1049, -0.2450,  0.3000],
        [ 0.2821,  0.2206, -0.2794,  0.3012,  0.2835],
        [ 0.0778, -0.1326,  0.2587,  0.1790, -0.1432],
        [ 0.0369,  0.6218,  0.1892,  0.6380,  0.1848]])

In [170]:
# in the above case, x2 is expanded automatically to match x1 dimension

In [172]:
x1*x2

tensor([[0.0342, 0.1613, 0.0923, 0.1029, 0.0641],
        [0.0312, 0.0427, 0.3278, 0.0074, 0.0883],
        [0.0169, 0.0687, 0.2184, 0.1562, 0.0853],
        [0.0065, 0.0072, 0.5559, 0.1229, 0.0073],
        [0.0044, 0.1386, 0.5123, 0.2479, 0.0672]])

In [173]:
x1

tensor([[0.6752, 0.9260, 0.1471, 0.3779, 0.3504],
        [0.6150, 0.2453, 0.5225, 0.0273, 0.4829],
        [0.3328, 0.3947, 0.3480, 0.5735, 0.4664],
        [0.1285, 0.0416, 0.8861, 0.4513, 0.0397],
        [0.0876, 0.7959, 0.8166, 0.9103, 0.3676]])

In [174]:
x2

tensor([[0.0507, 0.1742, 0.6274, 0.2723, 0.1829]])

In [176]:
torch.sum(x2, dim = 1)

tensor([1.3074])

In [177]:
torch.sum(x2, dim = 0)

tensor([0.0507, 0.1742, 0.6274, 0.2723, 0.1829])

In [178]:
val, ind = torch.max(x2, dim = 0)

In [179]:
val

tensor([0.0507, 0.1742, 0.6274, 0.2723, 0.1829])

In [180]:
ind

tensor([0, 0, 0, 0, 0])

In [181]:
val, ind = torch.max(x2, dim = 1)

In [182]:
val, ind

(tensor([0.6274]), tensor([2]))

In [186]:
float(val[0])

0.6274076700210571

In [187]:
torch.argmax(x2)

tensor(2)

In [189]:
torch.eq(x1, x2) # compare element wise

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [190]:
torch.mean(x2)

tensor(0.2615)

In [199]:
torch.sort(x2)

torch.return_types.sort(
values=tensor([[0.0507, 0.1742, 0.1829, 0.2723, 0.6274]]),
indices=tensor([[0, 1, 4, 3, 2]]))

In [203]:
torch.sort(x2).values.numpy()[0][0]

0.050659478

In [204]:
x2

tensor([[0.0507, 0.1742, 0.6274, 0.2723, 0.1829]])

In [207]:
torch.clamp(x2, min = 0.2, max = 0.5)

tensor([[0.2000, 0.2000, 0.5000, 0.2723, 0.2000]])

In [208]:
torch.any(x2)

tensor(True)

In [209]:
torch.all(x2)

tensor(True)

In [210]:
x = torch.arange(10)

In [211]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

In [212]:
x[x%2==0]

tensor([0, 2, 4, 6, 8])

In [214]:
indices = [2, 4, 6]
x[indices]

tensor([2, 4, 6])

In [219]:
torch.where(x>5, x, x*3) #if x>5, the value stays same else it is multiplied by 3

tensor([ 0,  3,  6,  9, 12, 15,  6,  7,  8,  9])

In [220]:
torch.tensor([0, 1, 2, 0, 1, 2, 0]).unique()

tensor([0, 1, 2])

In [221]:
x.ndim

1

In [222]:
# number of elements
x.numel()

10

In [226]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [227]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [228]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
# to change, do x = x.reshape(2, 5), reshape is best as its a copy, view references to the original

In [235]:
# transpose
x = torch.arange(10)
x = x.view(2, 5)

In [237]:
y = x.t()
y

tensor([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8],
        [4, 9]])

In [242]:
y.view(10)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [244]:
y.contiguous().view(10)

tensor([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [245]:
# or do with reshape
y.reshape(10)

tensor([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [251]:
torch.cat((x1, x2), dim = 0)

tensor([[0.6752, 0.9260, 0.1471, 0.3779, 0.3504],
        [0.6150, 0.2453, 0.5225, 0.0273, 0.4829],
        [0.3328, 0.3947, 0.3480, 0.5735, 0.4664],
        [0.1285, 0.0416, 0.8861, 0.4513, 0.0397],
        [0.0876, 0.7959, 0.8166, 0.9103, 0.3676],
        [0.0507, 0.1742, 0.6274, 0.2723, 0.1829]])

In [252]:
x1

tensor([[0.6752, 0.9260, 0.1471, 0.3779, 0.3504],
        [0.6150, 0.2453, 0.5225, 0.0273, 0.4829],
        [0.3328, 0.3947, 0.3480, 0.5735, 0.4664],
        [0.1285, 0.0416, 0.8861, 0.4513, 0.0397],
        [0.0876, 0.7959, 0.8166, 0.9103, 0.3676]])

In [253]:
x2

tensor([[0.0507, 0.1742, 0.6274, 0.2723, 0.1829]])

In [259]:
torch.cat((x1, x2.t()), dim = 1)

tensor([[0.6752, 0.9260, 0.1471, 0.3779, 0.3504, 0.0507],
        [0.6150, 0.2453, 0.5225, 0.0273, 0.4829, 0.1742],
        [0.3328, 0.3947, 0.3480, 0.5735, 0.4664, 0.6274],
        [0.1285, 0.0416, 0.8861, 0.4513, 0.0397, 0.2723],
        [0.0876, 0.7959, 0.8166, 0.9103, 0.3676, 0.1829]])

In [261]:
x2.view(-1)

tensor([0.0507, 0.1742, 0.6274, 0.2723, 0.1829])

In [262]:
batch = 10
x = torch.rand(batch, 2, 3)
x.view(batch, -1) # the batch dimension stays the same

tensor([[5.9193e-01, 6.7043e-01, 8.9463e-01, 6.8686e-02, 1.8031e-01, 1.3489e-01],
        [8.2590e-01, 4.7763e-01, 9.2965e-01, 4.8962e-01, 5.1542e-01, 4.6879e-02],
        [3.2792e-01, 1.5615e-01, 8.9290e-01, 1.1932e-01, 3.9968e-02, 6.8860e-01],
        [6.5710e-01, 2.1206e-02, 6.4820e-01, 1.0267e-01, 6.7212e-01, 5.0572e-01],
        [8.6395e-02, 9.0696e-01, 4.2996e-01, 6.2560e-03, 5.6212e-01, 9.4994e-01],
        [3.6279e-01, 9.6146e-01, 7.0715e-01, 2.2428e-03, 5.0325e-02, 3.7010e-02],
        [7.2905e-02, 7.3195e-04, 1.5468e-01, 4.3695e-01, 8.6835e-01, 8.3062e-01],
        [7.5589e-01, 2.0579e-01, 1.6815e-01, 1.0718e-01, 5.0122e-01, 9.7554e-02],
        [1.4254e-01, 4.6769e-01, 8.9754e-01, 2.1986e-01, 4.6113e-01, 7.6987e-02],
        [3.8628e-01, 9.6891e-01, 9.7560e-01, 1.3187e-01, 1.9162e-01, 7.2246e-01]])

In [264]:
x.view(batch, -1).shape

torch.Size([10, 6])

In [266]:
x

tensor([[[5.9193e-01, 6.7043e-01, 8.9463e-01],
         [6.8686e-02, 1.8031e-01, 1.3489e-01]],

        [[8.2590e-01, 4.7763e-01, 9.2965e-01],
         [4.8962e-01, 5.1542e-01, 4.6879e-02]],

        [[3.2792e-01, 1.5615e-01, 8.9290e-01],
         [1.1932e-01, 3.9968e-02, 6.8860e-01]],

        [[6.5710e-01, 2.1206e-02, 6.4820e-01],
         [1.0267e-01, 6.7212e-01, 5.0572e-01]],

        [[8.6395e-02, 9.0696e-01, 4.2996e-01],
         [6.2560e-03, 5.6212e-01, 9.4994e-01]],

        [[3.6279e-01, 9.6146e-01, 7.0715e-01],
         [2.2428e-03, 5.0325e-02, 3.7010e-02]],

        [[7.2905e-02, 7.3195e-04, 1.5468e-01],
         [4.3695e-01, 8.6835e-01, 8.3062e-01]],

        [[7.5589e-01, 2.0579e-01, 1.6815e-01],
         [1.0718e-01, 5.0122e-01, 9.7554e-02]],

        [[1.4254e-01, 4.6769e-01, 8.9754e-01],
         [2.1986e-01, 4.6113e-01, 7.6987e-02]],

        [[3.8628e-01, 9.6891e-01, 9.7560e-01],
         [1.3187e-01, 1.9162e-01, 7.2246e-01]]])

In [265]:
x.permute(0, 2, 1) # to let 1st dimension stay same, 2nd dimension to become 3rd and 3rd to become 2nd

tensor([[[5.9193e-01, 6.8686e-02],
         [6.7043e-01, 1.8031e-01],
         [8.9463e-01, 1.3489e-01]],

        [[8.2590e-01, 4.8962e-01],
         [4.7763e-01, 5.1542e-01],
         [9.2965e-01, 4.6879e-02]],

        [[3.2792e-01, 1.1932e-01],
         [1.5615e-01, 3.9968e-02],
         [8.9290e-01, 6.8860e-01]],

        [[6.5710e-01, 1.0267e-01],
         [2.1206e-02, 6.7212e-01],
         [6.4820e-01, 5.0572e-01]],

        [[8.6395e-02, 6.2560e-03],
         [9.0696e-01, 5.6212e-01],
         [4.2996e-01, 9.4994e-01]],

        [[3.6279e-01, 2.2428e-03],
         [9.6146e-01, 5.0325e-02],
         [7.0715e-01, 3.7010e-02]],

        [[7.2905e-02, 4.3695e-01],
         [7.3195e-04, 8.6835e-01],
         [1.5468e-01, 8.3062e-01]],

        [[7.5589e-01, 1.0718e-01],
         [2.0579e-01, 5.0122e-01],
         [1.6815e-01, 9.7554e-02]],

        [[1.4254e-01, 2.1986e-01],
         [4.6769e-01, 4.6113e-01],
         [8.9754e-01, 7.6987e-02]],

        [[3.8628e-01, 1.3187e-01],
  